### ISSUE TITLE
Update to sinon 1.12.2

### ISSUE THREAD

**Issue by DominikGuzei** [practicalmeteor/meteor-sinon#3]

**Comment by robot-lavaina** [comment]
Will do when I'm back from vacation.

**Comment by ryneeverett** [comment]
+1. Sinon is on 1.14.1 now.

I built v1.10.3 myself and diffed it with the script in this repo. The diff seem too significant to be due merely to compile dependency upgrades so I'm guessing it was manually edited, but I can't make much sense of the modifications.

Did changes to Sinon introduce new complications to packaging it for Meteor? @DominikGuzei, why did you stop maintaining your own meteor-sinon package in favor of this one?

**Comment by ryneeverett** [comment]
Well I ended up getting an updated version working with only minor modifications to the built script. It turned out that most of the additional lines I found in my v1.10.3 build are already in v1.14.1, which I find mystifying.

**Comment by DominikGuzei** [comment]
@ryneeverett I just needed this for `practicalmeteor:munit` but I also use my own version now :wink:

**Comment by rbabayoff** [comment]
Will update it myself soon. Will also try and get them to auto deploy it using https://autopublish.meteor.com/
