### ISSUE TITLE
Allow stubbing properties of objects that aren't plain objects.

### ISSUE THREAD

**Issue by benweissmann** [practicalmeteor/meteor-sinon#4]
In [Helpers.coffee, line 52](https://github.com/practicalmeteor/meteor-sinon/blob/b3a8d588e3505f01fb30b5908026c077868cc2d2/Helpers.coffee#L52), you check that the object whose property is going to be stubbed is an object.

This check fails for things that have properties but are not plain objects. For example, I can't stub `Router.go` in Iron Router because `Router` is a function (that also happens to have properties).

**Comment by rbabayoff** [comment]
OK, will take a look at it and see if I pass this through to sinon without checking it's an object, if it still works.
